/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarRentalSystem.Forms;

import java.awt.*;
import java.util.Arrays;

import javax.swing.*;

import CarRentalSystem.Pojos.User;
import CarRentalSystem.Utilities.UserHelper;
import CarRentalSystem.Utilities.UserSessionHandler;

/** @author H121709 */
public class AcountForm extends javax.swing.JFrame implements UserSessionHandler {

  UserHelper user = UserHelper.getInstance();

  /** Creates new form CreateAcountFrame */
  public AcountForm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jUsername = new javax.swing.JTextField();
    jPassword = new javax.swing.JTextField();
    jConfirm_password = new javax.swing.JTextField();
    jEmail = new javax.swing.JTextField();
    jPhone = new javax.swing.JTextField();
    jButtonAccount = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel3Password = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    user.addListener(this);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    //        jTextField2.addActionListener(new java.awt.event.ActionListener() {
    //            public void actionPerformed(java.awt.event.ActionEvent evt) {
    //                jTextField2ActionPerformed(evt);
    //            }
    //        });

    jButtonAccount.setText("Create Account");
    jButtonAccount.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {

            CreateAccount();
          }
        });

    jLabel1.setText("UserName");

    jLabel3Password.setText("Password");

    jLabel4.setText("Confirm Pasword");

    jLabel5.setText("Email");

    jLabel6.setText("Phone");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(
                                        jUsername,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        275,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel3Password)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(
                                        jPassword,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        275,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        jConfirm_password,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        275,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        jEmail,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        275,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jPhone,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                275,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        jButtonAccount,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        215,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(44, 44, 44)))))
                    .addContainerGap(163, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jUsername,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jPassword,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3Password))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jConfirm_password,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jEmail,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jPhone,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                            .addComponent(jLabel5))
                    .addGap(37, 37, 37)
                    .addComponent(
                        jButtonAccount,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        40,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void CreateAccount() {
    User newUser = new User();
    newUser.setUsername(jUsername.getText());
    newUser.setPassword(jPassword.getText());
    newUser.setPhone(jPhone.getText());
    newUser.setEmail(jEmail.getText());
    newUser.setAccountType("normal");
    UserHelper user = UserHelper.getInstance();
   isValidateAccount();
    if(isValidateAccount()){
      user.addNewUser(newUser);
      user.createNewUser();
    }
  }

  public boolean isValidateAccount() {
    // todo Anwar validate account
    // todo first check if user not already exist
    JTextField[] jTextFields = new JTextField[5];
    jTextFields[0] = jUsername;
    jTextFields[1] = jPassword;
    jTextFields[2] = jPhone;
    jTextFields[3] = jEmail;
    jTextFields[4] = jConfirm_password;

    boolean is_all_filedsNotEmpty =
        Arrays.stream(jTextFields)
            .allMatch(e -> (!e.getText().isEmpty()) && !(e.getText().length() == 0));
    boolean already_exist;
    try{
       already_exist  =
              user.getUsers()
                      .stream()
                      .filter(
                              o -> {
                                User validator = o;
                                return validator.getUsername().equals(jUsername.getText());
                              }).findFirst().isPresent();
    }catch (NullPointerException ex){
       already_exist = false;
    }


    boolean bothPasswordsMacthes = jPassword.getText().equals(jConfirm_password.getText());

    System.out.println(is_all_filedsNotEmpty + "  " + !already_exist + " " + bothPasswordsMacthes);

    return is_all_filedsNotEmpty && (!already_exist) && bothPasswordsMacthes;
  }

  private void jButtonAccountActionPerformed(
      java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonAccountActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_jButtonAccountActionPerformed

  private void jTextField2ActionPerformed(
      java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_jTextField2ActionPerformed

  /** @param args the command line arguments */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AcountForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AcountForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AcountForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AcountForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new AcountForm().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAccount;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3Password;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField jUsername;
  private javax.swing.JTextField jPassword;
  private javax.swing.JTextField jConfirm_password;
  private javax.swing.JTextField jEmail;
  private javax.swing.JTextField jPhone;

  @Override
  public void onNewAccountCreated() {
    //Todo Radcliffe show main Gui
    // Todo Radcliffe Exit this one
    // Todo Radcliffe show a message that says user account is created sccussefully
    AvailableVehicleForm jf = new AvailableVehicleForm();
    jf.setTitle("Available Vehicles");

    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    int width = gd.getDisplayMode().getWidth();
    int height = gd.getDisplayMode().getHeight();

    Point middle = new Point(width / 2, height / 2);
    Point newLocation = new Point(middle.x - (jf.getWidth() / 2), middle.y - (jf.getHeight() / 2));

    jf.pack();

    jf.setLocation(newLocation);

    jf.setVisible(true);

    System.out.println("OnSuccessAccount");
  }

  @Override
  public void onSuccessLogin() {}

  @Override
  public void onUnSuccessLogin() {}

  // End of variables declaration//GEN-END:variables

  //@Override //Todo check the correctness of this anwar I have remove it for testing
  public void onUnSuccessAccount() {
    // Todo show an error message as what they have toaught us in the module

    System.out.println("On Error Account");
  }
}
