/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarRentalSystem.Forms;

import java.awt.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import CarRentalSystem.Pojos.AvailableCars;
import CarRentalSystem.Pojos.RentedCars;
import CarRentalSystem.Utilities.CarsHelper;
import CarRentalSystem.Pojos.CurrentUser;

/** @author Radcliffe Brown-H000063206-CKIT-510-2-Week5-6 */
public class AvailableVehicleForm extends JFrame {

  /** Creates new form NumberConverterUI */
  public AvailableVehicleForm() {
    initComponents();
    myListBoxHandler();
  }

  //create new instance of list item
  HashSet<AvailableCars> uniqueSet = new HashSet<>();

  CarsHelper cars = CarsHelper.getInstance();
  DefaultListModel<String> myListBoxmodel = new DefaultListModel<>();

  int getSelectedCarOnce;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    myButtonGroup = new javax.swing.ButtonGroup();
    dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
    jPanelStartTime = new javax.swing.JPanel();
    jLabelStartTime = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jButtonConfirmBooking = new javax.swing.JButton();
    rentStartDate = new datechooser.beans.DateChooserCombo();
    rentEndDate = new datechooser.beans.DateChooserCombo();
    jLabel2 = new javax.swing.JLabel();
    jTextFieldUserDetails = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jListAvailableVehicles = new javax.swing.JList<>();
    jPanelImageHolder = new javax.swing.JPanel();
    jButtonRemove = new javax.swing.JButton();
    jButtonClose = new javax.swing.JButton();
    jButtonAdmin1 = new javax.swing.JButton();

    if(!CurrentUser.getType().equals("admin")){
      jButtonRemove.setEnabled(false);
      jButtonAdmin1.setEnabled(false);
    }
    jTextFieldUserDetails.setText(CurrentUser.getUsername());

    jListAvailableVehicles.addListSelectionListener(e -> listChangeListener(e));
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelStartTime.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Bookings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

    jLabelStartTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabelStartTime.setText("Start Time:");

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("End Time:");

    jButtonConfirmBooking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonConfirmBooking.setText("Confirm Booking");
    jButtonConfirmBooking.addActionListener(evt -> jButtonConfirmBookingActionPerformed());

    rentStartDate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(0, 0, 255),
                            true,
                            true,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 255),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(128, 128, 128),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.LabelPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.LabelPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(255, 0, 0),
                            false,
                            false,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    (datechooser.view.BackRenderer)null,
                    false,
                    true)));

    rentEndDate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(0, 0, 255),
                            true,
                            true,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 255),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(128, 128, 128),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.LabelPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(0, 0, 255),
                            false,
                            true,
                            new datechooser.view.appearance.swing.LabelPainter()),
                    new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                            new java.awt.Color(0, 0, 0),
                            new java.awt.Color(255, 0, 0),
                            false,
                            false,
                            new datechooser.view.appearance.swing.ButtonPainter()),
                    (datechooser.view.BackRenderer)null,
                    false,
                    true)));

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("End Time:");

    javax.swing.GroupLayout jPanelStartTimeLayout = new javax.swing.GroupLayout(jPanelStartTime);
    jPanelStartTime.setLayout(jPanelStartTimeLayout);
    jPanelStartTimeLayout.setHorizontalGroup(
            jPanelStartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStartTimeLayout.createSequentialGroup()
                            .addGroup(jPanelStartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelStartTimeLayout.createSequentialGroup()
                                            .addComponent(jLabelStartTime)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rentEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rentStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelStartTimeLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jButtonConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
    );
    jPanelStartTimeLayout.setVerticalGroup(
            jPanelStartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStartTimeLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                    .addGroup(jPanelStartTimeLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelStartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelStartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTextFieldUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rentStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStartTime)
                                    .addComponent(jLabel1))
                            .addContainerGap(127, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Vehicles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel4.setText("Number of available cars:"+cars.getAvailable().size());
    jLabel4.setToolTipText("");

    jListAvailableVehicles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jListAvailableVehicles.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane3.setViewportView(jListAvailableVehicles);

    javax.swing.GroupLayout jPanelImageHolderLayout = new javax.swing.GroupLayout(jPanelImageHolder);
    jPanelImageHolder.setLayout(jPanelImageHolderLayout);
    jPanelImageHolderLayout.setHorizontalGroup(
            jPanelImageHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanelImageHolderLayout.setVerticalGroup(
            jPanelImageHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 343, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(496, 496, 496)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelImageHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addContainerGap())
    );

    jButtonRemove.setText("Remove Car");
    jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBtnRemoveCarActionPerformed();
      }
    });

    jButtonClose.setText("Close");
    jButtonClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCloseActionPerformed(evt);
      }
    });

    jButtonAdmin1.setText("Add Car");
    jButtonAdmin1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        CarForm jf = new CarForm();
        jf.setTitle("Available Hire Cars");

        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();

        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle = new Point(width / 2, height / 2);
        Point newLocation = new Point(middle.x - (jf.getWidth() / 2),
                middle.y - (jf.getHeight() / 2));

        jf.pack();

        jf.setLocation(newLocation);

        jf.setVisible(true);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanelStartTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(171, 171, 171))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(871, Short.MAX_VALUE)
                                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdmin1, jButtonClose, jButtonRemove});

    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanelStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(653, Short.MAX_VALUE)
                                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAdmin1, jButtonClose, jButtonRemove});

    jPanelStartTime.getAccessibleContext().setAccessibleName("New Rental");

    pack();
  }
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">

  private void jBtnRemoveCarActionPerformed() {

    cars.getAvailable().remove(cars.findSelectedCar(myListBoxmodel.get(jListAvailableVehicles.getSelectedIndex())));
    cars.updateAvailableCars();
    myListBoxHandler();
  }

  private void jButtonConfirmBookingActionPerformed()
      throws java.lang.ArrayIndexOutOfBoundsException {
    Object[] options = {"Confirm", "CANCEL"};
    int selection =
        JOptionPane.showOptionDialog(
            null,
            "Your current booking information:\n"
                + "Rented Car: "
                + jListAvailableVehicles.getSelectedValue()
                + "\n"
                + "From: "
                + rentStartDate.getText()
                + "\n"
                + "To: "
                + rentEndDate.getText(),
            "Booking Conformation",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[0]);
    if (selection == 0) {

        RentedCars newRented = new RentedCars();
        newRented.setCarID(cars.findSelectedCar(jListAvailableVehicles.getSelectedValue().trim()).getCarID());
        newRented.setStartDate(rentStartDate.getText());
        newRented.setEndDate(rentEndDate.getText());
        newRented.setUsername(CurrentUser.getUsername());
        cars.getRentedCars().add(newRented);
        cars.newRent();
        myListBoxHandler();


    }
  }



  private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {
    System.exit(0);
  }
  //create new instance of list item
  //prevent the overwriting of previous entry

  private void listChangeListener(ListSelectionEvent e) {

    if (getSelectedCarOnce == 0) {
      System.out.println(
          jListAvailableVehicles.getSelectedValue()
              + " "
              + rentStartDate.getText()
              + " "
              + rentEndDate.getText());
       // cars.findSelectedCarById(jListAvailableVehicles.getSelectedValue().trim()).getCarID();
      getSelectedCarOnce++;
    } else {
      getSelectedCarOnce = 0;
    }
  }

  private void myListBoxHandler() {

      myListBoxmodel.removeAllElements();
    final int[] x = {1};
      List<Integer> available = new ArrayList<>();
      cars.getAvailable().forEach(e->available.add(e.getCarID()));

      List<Integer> rented = new ArrayList<>();
      cars.getRentedCars().forEach(e->rented.add(e.getCarID()));

      available.removeAll(rented);

      available.stream().forEach(id -> {
          AvailableCars e = cars.findSelectedCarById(id);
          myListBoxmodel.addElement(e.getCompany() + " " + e.getName() + " " + e.getModel());
      });

      jListAvailableVehicles.setModel(myListBoxmodel);
  }

  /** @param args the command line arguments */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AvailableVehicleForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AvailableVehicleForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AvailableVehicleForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AvailableVehicleForm.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new AvailableVehicleForm().setVisible(true));
  }

  // Variables declaration - do not modify
  private datechooser.beans.DateChooserCombo rentStartDate;
  private datechooser.beans.DateChooserCombo rentEndDate;
  private datechooser.beans.DateChooserDialog dateChooserDialog1;
  private javax.swing.JButton jButtonAdmin1;
  private javax.swing.JButton jButtonClose;
  private javax.swing.JButton jButtonConfirmBooking;
  private javax.swing.JButton jButtonRemove;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabelStartTime;
  private javax.swing.JList<String> jListAvailableVehicles;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanelImageHolder;
  private javax.swing.JPanel jPanelStartTime;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JLabel jTextFieldUserDetails;
  private javax.swing.ButtonGroup myButtonGroup;
  // End of variables declaration
}
